<?php

use Drupal\Core\Routing\RouteMatchInterface;
/**
 * Implements hook_help().
 */
function webform_handler_creates_node_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help 
    case 'help.page.webform_handler_cretes_node':
      return t(<<<'OUTPUT'
      <h2>About</h2>
      <p>Configurable handler for comparing two dates on a webform.</p>
OUTPUT
    );

  }
}
