<?php

use Drupal\Core\Routing\RouteMatchInterface;
/**
 * Implements hook_help().
 */
function webform_handler__rcd_generator_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help
    case 'help.page.webform_handler__rcd_generator':
      return t(<<<'OUTPUT'
      <h2>About</h2>
      <p>Configurable handler for _rcd_generator.</p>
OUTPUT
    );

  }
}
