<?php
setlocale(LC_ALL,"es_ES");
/**
 * @file
 * Example of how to use Drupal's mail API.
 */

use Drupal\Component\Utility\Html;

/**
 * @defgroupLiquidador1 Example: Email
 * @{
 * Example of how to use Drupal's mail API.
 *
 * This example module provides two different examples of the Drupal email API:
 *  - Defines a simple contact form and shows how to use MailManager::mail()
 *    to send an e-mail (defined in hook_mail()) when the form is submitted.
 *  - Shows how modules can alter emails defined by other Drupal modules or
 *    core using hook_mail_alter by attaching a custom signature before
 *    they are sent.
 */

/**
 * Implements hook_mail().
 *
 * This hook defines a list of possible e-mail templates that this module can
 * send. Each e-mail is given a unique identifier, or 'key'.
 *
 * $message comes in with some standard properties already set: 'to' address,
 * 'from' address, and a set of default 'headers' from MailManager::mail(). The
 * goal of hook_mail() is to set the message's 'subject' and 'body' properties,
 * as well as make any adjustments to the headers that are necessary.
 *
 * The $params argument is an array which can hold any additional data required
 * to build the mail subject and body; for example, user-entered form data, or
 * some context information as to where the mail request came from.
 *
 * Note that hook_mail() is not actually a hook. It is only called for a single
 * module, the module named in the first argument of MailManager::mail(). So
 * it's a callback of a type, but not a hook.
 */
function Liquidadorepa_mail($key, &$message, $params) {
  // Each message is associated with a language, which may or may not be the
  // current user's selected language, depending on the type of e-mail being
  // sent. This $options array is used later in the t() calls for subject
  // and body to ensure the proper translation takes effect.
  $options = [
    'langcode' => $message['langcode'],
  ];

  switch ($key) {
   // Send a simple message from the contact form.
   case 'red':


    $from = \Drupal::config('system.site')->get('mail');
    $message['subject'] = t('Mensaje enviado por', ['@site-name' => $from], $options);
    // Note that the message body is an array, not a string.
    $account = \Drupal::currentUser();

    $message['body'][] = t('<p>'.'En virtud de la autoliquidación por usted realizada el día , le enviamos liquidación adjunta.'.'</p>'.'
    Formas de pago: La anterior liquidación podrá ser canceladas dentro de los cinco (5) días siguientes al recibo de este correo a través de los siguientes medios:'.'</p><p>'.'

    1. Ingresando al botón de pago en el siguiente linkhttps://www.psepagos.co/PSEHostingUI/ShowTicketOffice.aspx?ID=11065 y siguiendo los pasos como se indica en el instructivo adjunto.'.'</p><p>'.'

    2. Mediante consignación en la cuenta de ahorro No. 43300400033-0 en cualquier oficina del banco GNB SUDAMERIS, a favor del Establecimiento Público Ambiental EPA Cartagena Nit 806013999-2.
    Recomendaciones:'.'</p><p>'.'
    Una vez verificado el pago, el Establecimiento Publico Ambiental EPA Cartagena, le enviará dentro de las 24 horas hábiles siguientes el radicado de su solicitud, comunicación de rechazo o solicitud de documentación adicional. Una vez subsanada su solicitud se le asignará un numero de radicado el cual será notificado dentro de las siguientes 24 horas hábiles a través del correo electrónico suministrado por usted.'.'</p>'.'
    Para más información favor comunicarse a la dirección de correo electrónico atenciónalciudadano@epacartagena.gov.co al teléfono (035) 6421316 Ext 203. O acérquese a nuestras oficinas ubicadas en Manga 4ta Avenida Edif SEA PORT.', ['@name' => $account->getAccountName()], $options);
    // Because this is just user-entered text, we do not need to translate it.
    // Since user-entered text may have unintentional HTML entities in it like
    // '<' or '>', we need to make sure these entities are properly escaped,
    // as the body will later be transformed from HTML to text, meaning
    // that a normal use of '<' will result in truncation of the message.
  //  $message['body'][] = Html::escape($params['message']);

    break;
}
}

/**
 * Implements hook_mail_alter().
 *
 * This function is not required to send an email using Drupal's mail system.
 *
 * hook_mail_alter() provides an interface to alter any aspect of email sent by
 * Drupal. You can use this hook to add a common site footer to all outgoing
 * email, add extra header fields, and/or modify the email in anyway. HTML-izing
 * the outgoing email is one possibility.
 */
function Liquidadorepa_mail_alter(&$message) {
 // For the purpose of this example, modify all the outgoing messages and
  // attach a site signature. The signature will be translated to the language
  // in which message was built.
  $options = [
    'langcode' => $message['langcode'],
  ];

  $signature = t("\n--\n Cobros EPA.", [], $options);

  if (is_array($message['body'])) {
    $message['body'][] = $signature;
  }
  else {
    // Some modules use the body as a string, erroneously.
    $message['body'] .= $signature;
  }
}

/**
 * @} End of "defgroup Liquidador1".
 */
